curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/lex-web-ui-loader.css --output public/lex-web-ui-loader.css
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/lex-web-ui-loader.min.css --output public/lex-web-ui-loader.min.css
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/lex-web-ui-loader.min.js --output public/lex-web-ui-loader.min.js
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/lex-web-ui.min.css --output public/lex-web-ui.min.css
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/lex-web-ui.min.js --output public/lex-web-ui.min.js
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/wav-worker.min.js --output public/wav-worker.min.js
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/0.17.7_dist_vuetify.min.css --output public/0.17.7_dist_vuetify.min.css
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/0.17.7_dist_vuetify.min.js --output public/0.17.7_dist_vuetify.min.js 
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/3.4.0_dist_vuex.min.js --output public/3.4.0_dist_vuex.min.js
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/2.6.11_dist_vue.min.js --output public/2.6.11_dist_vue.min.js
curl https://raw.githubusercontent.com/aws-samples/aws-lex-web-ui/master/dist/aws-sdk-2.903.0.min.js --output public/aws-sdk-2.903.0.min.js